# Generated by Django 3.0.6 on 2021-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210515_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcoordinatorrelation',
            name='git_url',
        ),
        migrations.AddField(
            model_name='projectcoordinatorrelation',
            name='git_backend_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='projectcoordinatorrelation',
            name='git_frontend_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
