# Generated by Django 3.0.6 on 2021-09-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210928_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcoordinatorrelation',
            old_name='git_frontend_url',
            new_name='git_url',
        ),
    ]
