# Generated by Django 3.0.6 on 2021-09-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0006_meetingminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserList',
            name='git_username',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
