# Generated by Django 3.1.13 on 2021-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0009_confluenceupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceNewUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('displayName', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'confluence_newest_page',
            },
        ),
    ]
