# Generated by Django 3.1.13 on 2021-10-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0010_confluencenewupdate'),
        ('confluence', '0010_individualconfluencecontribution_attendence_count'),
    ]

    operations = [
    ]
