# Generated by Django 3.1.13 on 2021-10-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0011_confluenceupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='confluenceupdate',
            name='space_key',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
