# Generated by Django 3.0.6 on 2021-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'git_commit',
            },
        ),
        migrations.CreateModel(
            name='GitCommitCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('commit_counts', models.CharField(max_length=256)),
                ('query_date', models.IntegerField()),
            ],
            options={
                'db_table': 'git_commit_counts',
            },
        ),
        migrations.CreateModel(
            name='GitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('file_count', models.IntegerField()),
                ('class_count', models.IntegerField()),
                ('function_count', models.IntegerField()),
                ('code_lines_count', models.IntegerField()),
                ('declarative_lines_count', models.IntegerField()),
                ('executable_lines_count', models.IntegerField()),
                ('comment_lines_count', models.IntegerField()),
                ('comment_to_code_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'git_metrics',
            },
        ),
        migrations.CreateModel(
            name='StudentCommitCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=256)),
                ('relation_id', models.CharField(max_length=256, null=True)),
                ('commit_counts', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'student_commit_counts',
            },
        ),
    ]
