# Generated by Django 3.0.6 on 2021-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0003_gitcommit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitmetrics',
            name='source',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
