# Generated by Django 3.0.6 on 2021-10-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0004_gitmetrics_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('code_lines_count', models.IntegerField()),
                ('declarative_lines_count', models.IntegerField()),
                ('executable_lines_count', models.IntegerField()),
                ('comment_lines_count', models.IntegerField()),
                ('comment_to_code_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'file_metrics',
            },
        ),
    ]
