# Generated by Django 3.0.6 on 2021-10-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0005_filemetrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemetrics',
            old_name='declarative_lines_count',
            new_name='blank_lines_count',
        ),
        migrations.RemoveField(
            model_name='filemetrics',
            name='executable_lines_count',
        ),
    ]
