# Generated by Django 3.0.6 on 2021-10-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0007_auto_20211011_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitmetrics',
            name='CountDeclFile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
