# Generated by Django 3.0.6 on 2021-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0008_gitmetrics_countdeclfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetrics',
            name='CountDeclFunction',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
