# Generated by Django 3.0.6 on 2021-10-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0009_filemetrics_countdeclfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('commit', models.IntegerField()),
                ('source', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'git_contribution',
            },
        ),
    ]
