# Generated by Django 3.0.6 on 2021-10-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0010_gitcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcontribution',
            name='space_key',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
