# Generated by Django 3.0.6 on 2021-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0012_auto_20211014_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='commitChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('total', models.CharField(max_length=512)),
                ('additions', models.CharField(max_length=256)),
                ('deletions', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'commit_change',
            },
        ),
        migrations.DeleteModel(
            name='GitLastCommit',
        ),
    ]
