# Generated by Django 3.0.6 on 2021-10-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0013_auto_20211015_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitchange',
            name='space_key',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
