# Generated by Django 3.0.6 on 2021-10-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0014_commitchange_space_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitchange',
            name='additions',
            field=models.IntegerField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commitchange',
            name='deletions',
            field=models.IntegerField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commitchange',
            name='total',
            field=models.IntegerField(max_length=512),
        ),
    ]
