# Generated by Django 3.0.6 on 2021-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0015_auto_20211015_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcontribution',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
