# Generated by Django 3.0.6 on 2021-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0016_gitcontribution_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitchange',
            name='additions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commitchange',
            name='deletions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commitchange',
            name='total',
            field=models.IntegerField(),
        ),
    ]
